---
- name: Waf configure
  command: "./waf configure"
  args:
    chdir: "{{ home_location }}/ns-allinone-{{ NS3_VERSION }}/ns-{{ NS3_VERSION }}"
  register: gg
  tags: ns3
- name: Waf apiscan
  command: "./waf --apiscan={{ item }}"
  with_items:
    - netanim
    - wifi
    - lte
  args:
    chdir: "{{ home_location }}/ns-allinone-{{ NS3_VERSION }}/ns-{{ NS3_VERSION }}"
  async: 0
  poll: 0
  ignore_errors: true
  tags: ns3
- name: Waf build
  command: "./waf build"
  args:
    chdir: "{{ home_location }}/ns-allinone-{{ NS3_VERSION }}/ns-{{ NS3_VERSION }}"
  async: 0
  poll: 0
  ignore_errors: true
  tags: ns3
- name: Waf install
  command: "./waf install"
  args:
    chdir: "{{ home_location }}/ns-allinone-{{ NS3_VERSION }}/ns-{{ NS3_VERSION }}"
  tags: ns3
- name: Configure dynamic linker run-time bindings
  command: "ldconfig"
  tags: ns3
- name: Remove NS3 source code
  file:
    path: "{{ home_location }}/ns-allinone-{{ NS3_VERSION }}.tar.bz2"
    state: absent
  tags: ns3
